baseURL = "http://localhost:1313/"
title = "Careless"
theme = "hugo-bearblog"
paginate = 15

[params]
  custom_css = "<style>body { background-color: #f2f4ee !important; color: #2e4732 !important; } a { color: #2e4732 !important; } header a, nav a:first-child, .title { display: none !important; } h1 { font-size: 1.8rem; font-weight: 700; margin-top: 1rem; }</style>"
