baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Careless"
theme = "hugo-bearblog"
paginate = 15

[params]
  custom_css = "<style>body { background-color: #f2f4ee !important; color: #2e4732 !important; } a { color: #2e4732 !important; }</style>"
